#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Akshay Ranganath's Blogs
author: rakshay 


#adding twitter details
twitter:
  site: Akshay Ranganath's Blogs
  username: rakshay

# Short bio or description (displayed in the header)
description: Blogs about Media Optimization, Web Performance, SEO and web technology.
tagline: Musings from a Tech Entrepreneur

paginate: 8
paginate_path: '/blog/page:num'

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://akshayranganath-res.cloudinary.com/image/upload/f_auto,q_auto/github_profile.jpg


logo: https://akshayranganath-res.cloudinary.com/image/upload/f_auto,q_auto/github_profile.jpg
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: akshayranganath
  instagram:
  linkedin: akshayranganath
  pinterest:
  rss: rss # just type anything here for a working RSS icon
  twitter: rakshay
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
# disqus: akshayranganath

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-92984102-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://akshayranganath.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed #:expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag # Add SEO related tags and JSON-LD
  - jekyll-paginate # Adding pagination capability
  - jekyll-redirect-from #redirect functionalit

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# inspired by https://github.com/codinfox/codinfox-lanyon
# Adding category and tags support
categories:
  type: liquid
  path: /categories/
tags:
  type: liquid
  path: /tags/

nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://akshayranganath.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'
